rm(list = ls())
letters = read.csv("letters_ABPR.csv")
str(letters)
letters$isB = as.factor(letters$letter == "B")

#problem1
library(caTools)
set.seed(1000)
spl = sample.split(letters$isB , SplitRatio = 0.5)
train = subset(letters , spl==TRUE)
test = subset(letters, spl ==FALSE)
prop.table(table(test$isB))
CARTb = rpart(isB ~ . - letter, data=train, method="class")
pred.isB = predict(CARTb, newdata = test, type = "class")
table(test$isB, pred.isB)

library(randomForest)
set.seed(1000)
CARTb.rF = randomForest(isB ~ . - letter, data = train)
pred.rF.isB = predict(CARTb.rF, newdata = test, type = "class")
table(test$isB, pred.rF.isB)

#problem2
letters$letter = as.factor( letters$letter )
set.seed(2000)
spl = sample.split(letters$letter , SplitRatio = 0.5)
train = subset(letters , spl==TRUE)
test = subset(letters, spl ==FALSE)
bl.accuracy =max(table(test$letter)) / nrow(test)
CARTletter = rpart(letter ~ . - isB, data=train, method="class")
pred.letter = predict(CARTletter, newdata = test, type = "class")
table(test$letter, pred.letter)
set.seed(1000)
CARTletter.rF = randomForest(letter ~ . - isB, data = train)
pred.rF.letter = predict(CARTletter.rF, newdata = test, type = "class")
table(test$letter, pred.rF.letter)
