rm(list = ls())
gerber = read.csv("gerber.csv")
str(gerber)
prop.table(table(gerber$voting))
summary(gerber$voting)
summary(gerber)
ci = table(gerber$voting==1 , gerber$civicduty)
ci[4]/(ci[3] + ci[4])
ha = table(gerber$voting==1 , gerber$hawthorne)
ha[4]/(ha[3] + ha[4])
se = table(gerber$voting==1 , gerber$self)
se[4]/(se[3] + se[4])
ne = table(gerber$voting==1 , gerber$neighbors)
ne[4]/(ne[3] + ne[4])

tapply(gerber$voting, gerber$civicduty, mean)
tapply(gerber$voting, gerber$hawthorne, mean)
tapply(gerber$voting, gerber$self, mean)
tapply(gerber$voting, gerber$neighbors, mean)

votelm = glm(voting ~ civicduty + hawthorne + self + neighbors, family="binomial", data = gerber)
summary(votelm)
predictvote = predict(votelm , type="response")
t = 0.5
a = table(gerber$voting, predictvote >= t)
accuracy = (a[1] + a[4])/ sum(a)

library(ROCR)
ROCRpredTest = prediction(predictvote, gerber$voting)
auc = as.numeric(performance(ROCRpredTest,"auc")@y.values)
auc

library(rpart)
library(rpart.plot)
CARTmodel = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber)
prp(CARTmodel)
CARTmodel2 = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber, cp=0.0)
prp(CARTmodel2)
CARTmodel3 = rpart(voting ~ civicduty + hawthorne + self + neighbors + sex, data=gerber, cp=0.0)
prp(CARTmodel3)
CARTmodel4 = rpart(voting ~ control, data=gerber, cp=0.0)
prp(CARTmodel4, digits = 6)
CARTmodel5 = rpart(voting ~ control+ sex, data=gerber, cp=0.0)
prp(CARTmodel5, digit = 6)


LogModelSex = glm(voting ~ control + sex , family="binomial", data = gerber)
summary(LogModelSex)
Possibilities = data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
predict(LogModelSex, newdata=Possibilities, type="response")
LogModel2 = glm(voting ~ sex + control + sex:control, data=gerber, family="binomial")
summary(LogModel2)
predict(LogModel2, newdata=Possibilities, type="response")
