pisaTrain = read.csv("pisa2009train.csv")
pisaTest = read.csv("pisa2009test.csv")
str(pisaTrain)
summary(pisaTrain)
str(pisaTest)
summary(pisaTest)
tapply(pisaTrain$readingScore,pisaTrain$male,mean)
pisaTrain = na.omit(pisaTrain)
pisaTest = na.omit(pisaTest)
str(pisaTrain)
summary(pisaTrain)
str(pisaTest)
summary(pisaTest)